version: '3'

services:
  node1:
    build: ./front
    ports:
      - "81:80"
  node2:
    build: ./front
    ports:
      - "82:80"
  node3:
    build: ./front
    ports:
      - "83:80"
  node4:
    build: ./front
    ports:
      - "84:80"
  node5:
    build: ./front
    ports:
      - "85:80"
  nginx:
    build: ./nginx-front
    ports:
      - "80:80"
    depends_on:
     - node1
     - node2
     - node3
     - node4
     - node5
