version: '3'

services:
  node1:
    build: ./front
    ports:
      - "8081:8080"
  node2:
    build: ./front
    ports:
      - "8082:8080"
  node3:
    build: ./front
    ports:
      - "8083:8080"
  nginx:
    build: ./nginx-front
    ports:
      - "8080:8080"
    depends_on:
     - node1
     - node2
     - node3
