version: '3'

services:
  node1:
    build: ./front
    ports:
      - "81:80"
  node2:
    build: ./front
    ports:
      - "82:80"
  node3:
    build: ./front
    ports:
      - "83:80"
  node4:
    build: ./front
    ports:
      - "84:80"
  node5:
    build: ./front
    ports:
      - "85:80"
  nginx_front:
    build: ./nginx-front
    ports:
      - "80:80"
    depends_on:
     - node1
     - node2
     - node3
     - node4
     - node5
  mongo1:
    hostname: mongo_1
    container_name: mongo_1
    image: mongo:4.1
    ports:
      - "40001:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo_2
    container_name: mongo_2
    image: mongo:4.1
    ports:
      - "40002:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod","--bind_ip_all", "--replSet", "rs0" ]
  mongo-config:
    hostname: mongo-config
    container_name: mongo-config
    image: mongo:4.1
    volumes:
      - ./mongo/db-init.sh:/mongo/db-isudonit.sh
      - ./mongo/init.js:/mongo/init.js
    entrypoint: [ "bash" , "/mongo/db-init.sh" ]

