version: '3'

services:
  node1:
    build: ./front
    ports:
      - "81:84"
  node2:
    build: ./front
    ports:
      - "82:84"
  node3:
    build: ./front
    ports:
      - "83:84"
  nginx:
    build: ./nginx-front
    ports:
      - "84:84"
    depends_on:
     - node1
     - node2
     - node3
