version: '3'

services:
  node1:
    build: ./front
    ports:
      - "85:84"
  node2:
    build: ./front
    ports:
      - "86:84"
  node3:
    build: ./front
    ports:
      - "87:84"
  nginx_front:
    build: ./nginx-front
    ports:
      - "84:84"
    depends_on:
     - node1
     - node2
     - node3

